# Installs the latest (or a pinned) lazynats release for Windows (x64).
#
#   iwr -useb https://raw.githubusercontent.com/MiloszKrajewski/lazynats/main/install/windows.ps1 | iex
#
# Environment:
#   LAZYNATS_VERSION  install this version instead of the latest (e.g. 1.2.3)
#   LAZYNATS_HOME     install root (default: %LOCALAPPDATA%\Programs\lazynats)
#   LAZYNATS_BIN      directory for the launcher (default: %USERPROFILE%\.local\bin)
#
# Layout:
#   %LAZYNATS_HOME%\<version>\...     extracted release (exe + native libs)
#   %LAZYNATS_BIN%\lazynats.exe       tiny launcher (generated by stubgen) pointing at that version
#
# There is no uninstaller: delete the two locations above (and, if you like, the LAZYNATS_BIN entry
# in your user PATH). Everything this script touches is echoed as it goes.

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'   # Windows PowerShell 5.1 downloads are very slow with progress on

$Repo = 'MiloszKrajewski/lazynats'
$Releases = "https://github.com/$Repo/releases"
$StubgenUrl = 'https://github.com/MiloszKrajewski/stubgen/releases/download/1.0.0/stubgen.exe'

$HomeDir = if ($env:LAZYNATS_HOME) { $env:LAZYNATS_HOME } else { Join-Path $env:LOCALAPPDATA 'Programs\lazynats' }
$BinDir = if ($env:LAZYNATS_BIN) { $env:LAZYNATS_BIN } else { Join-Path $env:USERPROFILE '.local\bin' }

function Get-LatestVersion {
	# /releases/latest redirects to /releases/tag/<version>; no API call, so no rate limit.
	$response = Invoke-WebRequest -Uri "$Releases/latest" -Method Head -UseBasicParsing
	$base = $response.BaseResponse
	$uri = if ($base.ResponseUri) { $base.ResponseUri } else { $base.RequestMessage.RequestUri }   # 5.1 vs 7+
	$version = $uri.AbsoluteUri.TrimEnd('/').Split('/')[-1]
	if (-not $version -or $version -eq 'latest') { throw 'could not determine the latest version' }
	$version
}

function Test-Checksum($Archive, $ChecksumFile) {
	$expected = ((Get-Content $ChecksumFile -Raw).Trim() -split '\s+')[0]
	$actual = (Get-FileHash $Archive -Algorithm SHA256).Hash
	if ($actual -ne $expected) { throw "checksum mismatch for $(Split-Path $Archive -Leaf)" }
}

function Get-PathEntryKey($Entry) {
	[Environment]::ExpandEnvironmentVariables($Entry).Trim().TrimEnd('\').ToLowerInvariant()
}

function Add-ToUserPath($Dir) {
	# Edit the registry value directly: [Environment]::SetEnvironmentVariable would flatten
	# REG_EXPAND_SZ and turn any %VAR% entries in the user's PATH into literal text.
	$key = [Microsoft.Win32.Registry]::CurrentUser.OpenSubKey('Environment', $true)
	try {
		$current = [string]$key.GetValue('Path', '', 'DoNotExpandEnvironmentNames')
		$entries = $current -split ';' | Where-Object { $_ }
		$wanted = Get-PathEntryKey $Dir
		if ($entries | Where-Object { (Get-PathEntryKey $_) -eq $wanted }) {
			Write-Host "PATH:      $Dir is already in your user PATH (unchanged)"
			return
		}
		$key.SetValue('Path', (($entries + $Dir) -join ';'), 'ExpandString')
	}
	finally { $key.Dispose() }

	# Registry writes don't notify running programs; broadcast so new terminals pick it up.
	Add-Type -Namespace Win32 -Name Native -MemberDefinition @'
[System.Runtime.InteropServices.DllImport("user32.dll", SetLastError = true, CharSet = System.Runtime.InteropServices.CharSet.Auto)]
public static extern System.IntPtr SendMessageTimeout(System.IntPtr hWnd, uint Msg, System.UIntPtr wParam, string lParam, uint flags, uint timeout, out System.UIntPtr result);
'@
	$result = [UIntPtr]::Zero
	[void][Win32.Native]::SendMessageTimeout([IntPtr]0xffff, 0x1A, [UIntPtr]::Zero, 'Environment', 2, 5000, [ref]$result)

	$env:Path = "$env:Path;$Dir"
	Write-Host "PATH:      added $Dir to your user PATH (open a new terminal to pick it up)"
}

if (-not [Environment]::Is64BitOperatingSystem) { throw "32-bit Windows is not supported; see $Releases" }

$version = if ($env:LAZYNATS_VERSION) { $env:LAZYNATS_VERSION } else { Get-LatestVersion }
$archive = "lazynats-$version-windows-x64.zip"
$base = "$Releases/download/$version"

Write-Host "Installing lazynats $version (windows-x64)..."

$tmp = Join-Path ([IO.Path]::GetTempPath()) "lazynats-install-$([Guid]::NewGuid().ToString('N'))"
New-Item -ItemType Directory -Path $tmp | Out-Null
try {
	$zip = Join-Path $tmp $archive
	Invoke-WebRequest -Uri "$base/$archive" -OutFile $zip -UseBasicParsing
	$sum = "$zip.sha256"
	try { Invoke-WebRequest -Uri "$base/$archive.sha256" -OutFile $sum -UseBasicParsing; $haveSum = $true }
	catch { $haveSum = $false }
	if ($haveSum) { Test-Checksum $zip $sum } else { Write-Warning "no checksum published for $archive, skipping verification" }

	$target = Join-Path $HomeDir $version
	$partial = "$target.partial"
	New-Item -ItemType Directory -Path $HomeDir -Force | Out-Null
	if (Test-Path $partial) { Remove-Item $partial -Recurse -Force }
	Expand-Archive -Path $zip -DestinationPath $partial

	$exe = Get-ChildItem $partial -Recurse -Filter 'lazynats.exe' | Select-Object -First 1
	if (-not $exe) { throw "lazynats.exe not found in $archive" }
	$relative = $exe.FullName.Substring($partial.Length)

	# Swap into place only after a complete extraction, so a failed run never leaves a half-installed version.
	if (Test-Path $target) {
		try { Remove-Item $target -Recurse -Force }
		catch { throw "cannot replace $target (is lazynats running?): $($_.Exception.Message)" }
	}
	Move-Item $partial $target
	$installed = "$target$relative"
	Write-Host "Installed: $installed"

	# The launcher is regenerated every time, so it always points at the version just installed.
	$stubgen = Join-Path $tmp 'stubgen.exe'
	Invoke-WebRequest -Uri $StubgenUrl -OutFile $stubgen -UseBasicParsing
	$stub = Join-Path $tmp 'lazynats.exe'
	# stubgen bakes everything after the output path in as the command line, so the path is quoted for it.
	$process = Start-Process -FilePath $stubgen -ArgumentList "`"$stub`" `"`"`"$installed`"`"`"" -Wait -PassThru -WindowStyle Hidden
	if ($process.ExitCode -ne 0 -or -not (Test-Path $stub)) { throw "stubgen failed (exit code $($process.ExitCode))" }

	New-Item -ItemType Directory -Path $BinDir -Force | Out-Null
	$launcher = Join-Path $BinDir 'lazynats.exe'
	try { Move-Item $stub $launcher -Force }
	catch { throw "cannot replace $launcher (is lazynats running?): $($_.Exception.Message)" }
	Write-Host "Launcher:  $launcher -> $installed"

	Add-ToUserPath $BinDir

	Write-Host ''
	Write-Host 'To uninstall, delete:'
	Write-Host "  $HomeDir   (all installed versions)"
	Write-Host "  $launcher"
}
finally {
	Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue
}
