<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ConsoleAppFramework" Version="5.7.13" />
    <PackageReference Include="NATS.Client.JetStream" Version="3.2.0" />
    <PackageReference Include="NATS.Client.KeyValueStore" Version="3.2.0" />
    <PackageReference Include="NATS.Client.ObjectStore" Version="3.2.0" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.11" />
    <PackageReference Include="System.Reactive" Version="7.0.0" />
    <PackageReference Include="Terminal.Gui" Version="2.4.17" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>

</Project>
